//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuroraTranslationTool.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuroraTranslationTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sprites {
            get {
                object obj = ResourceManager.GetObject("sprites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n=&quot;Unknown&quot; x=0 y=0
        ///n=&quot;Abkhazia&quot; x=64 y=0
        ///n=&quot;Afghanistan&quot; x=128 y=0
        ///n=&quot;Aland&quot; x=192 y=0
        ///n=&quot;Albania&quot; x=256 y=0
        ///n=&quot;Algeria&quot; x=320 y=0
        ///n=&quot;American Samoa&quot; x=384 y=0
        ///n=&quot;Andorra&quot; x=448 y=0
        ///n=&quot;Angola&quot; x=512 y=0
        ///n=&quot;Anguilla&quot; x=576 y=0
        ///n=&quot;Antarctica&quot; x=640 y=0
        ///n=&quot;Antigua and Barbuda&quot; x=704 y=0
        ///n=&quot;Argentina&quot; x=768 y=0
        ///n=&quot;Armenia&quot; x=832 y=0
        ///n=&quot;Aruba&quot; x=896 y=0
        ///n=&quot;Australia&quot; x=960 y=0
        ///n=&quot;Austria&quot; x=1024 y=0
        ///n=&quot;Azerbaijan&quot; x=1088 y=0
        ///n=&quot;Bahamas&quot; x=1152 y=0
        ///n=&quot;Bahrain&quot; x=1216 y=0
        ///n=&quot;Bangladesh&quot; x=1280 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spritesdata {
            get {
                return ResourceManager.GetString("spritesdata", resourceCulture);
            }
        }
    }
}
